---
apiVersion: v1
kind: Secret
metadata:
  name: ftgo-mysql-secrets
  namespace: ftgo
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-user: mysqluser
  mysql-password: mysqlpw
---
apiVersion: v1
kind: Secret
metadata:
  name: ftgo-consumer-db-secrets
  namespace: ftgo
type: Opaque
stringData:
  consumer-db-username: ftgo_consumer_service_user
  consumer-db-password: ftgo_consumer_service_password

